---  
spring:
  rabbitmq:
    host: localhost
    port: 5672
    username: zhb
    password: zhb
    virtual-host: cloud-zhb
eureka:
  instance:
    preferIpAddress: true
    statusPageUrlPath: /info.html
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
turbine:
  appConfig: love-origami-domain,cloud-cust-domain,love-life-app
  aggregator:
    clusterConfig: MAIN
  clusterNameExpression: metadata['cluster']