---  
spring:
  --rabbitmq:
    host: 10.130.202.57
    port: 5672
    username: hie_cloud
    password: hie_cloud123456
    VirtualHost: tk-hie
eureka:
  instance:
    preferIpAddress: true
    statusPageUrlPath: /info.html
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
turbine:
  appConfig: love-life-app,love-origami-domain
  aggregator:
    clusterConfig: MAIN
  clusterNameExpression: metadata['cluster']